"""Evaluate fixed/recursive dense, BM25, hybrid, and reranked retrieval."""

import json
from pathlib import Path

from qdrant_client import QdrantClient

from backend.app.config import Settings
from backend.app.embeddings.sentence_transformer import SentenceTransformerEmbedder
from backend.app.evaluation.dataset import RetrievalEvaluationQuery, read_queries
from backend.app.evaluation.metrics import RetrievalEvaluation, evaluate_retriever
from backend.app.ingestion.pipeline import read_chunks
from backend.app.retrieval.dense import QdrantDenseRetriever
from backend.app.retrieval.hybrid import HybridRetriever
from backend.app.retrieval.reranker import CrossEncoderScorer, RerankedRetriever
from backend.app.retrieval.sparse import BM25Retriever

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _resolved_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def _load_labels(strategy: str) -> list[RetrievalEvaluationQuery]:
    path = PROJECT_ROOT / f"data/evaluation/retrieval_queries_{strategy}.jsonl"
    return read_queries(path, RetrievalEvaluationQuery)


def _rank(item: object) -> int:
    rank = getattr(item, "first_relevant_rank", None)
    return int(rank) if rank is not None else 1_000_000


def _comparison(evaluations: dict[str, RetrievalEvaluation]) -> dict[str, object]:
    dense = evaluations["dense_recursive"]
    sparse = evaluations["bm25_recursive"]
    hybrid = evaluations["hybrid_recursive"]
    reranked = evaluations["reranked_recursive"]
    fixed = evaluations["dense_fixed"]

    dense_by_id = {item.query_id: item for item in dense.per_query}
    sparse_by_id = {item.query_id: item for item in sparse.per_query}
    dense_wins = [
        query_id
        for query_id in dense_by_id
        if _rank(dense_by_id[query_id]) < _rank(sparse_by_id[query_id])
    ]
    bm25_wins = [
        query_id
        for query_id in dense_by_id
        if _rank(sparse_by_id[query_id]) < _rank(dense_by_id[query_id])
    ]
    failures = [
        item.query_id
        for item in reranked.per_query
        if item.relevant_chunk_ids and item.first_relevant_rank is None
    ]

    return {
        "dense_vs_bm25": {
            "dense_wins": dense_wins,
            "bm25_wins": bm25_wins,
            "ties": len(dense_by_id) - len(dense_wins) - len(bm25_wins),
        },
        "fixed_vs_recursive_dense": {
            "recall_at_5_delta": round(
                dense.metrics.recall_at_k["5"] - fixed.metrics.recall_at_k["5"], 6
            ),
            "mrr_at_5_delta": round(dense.metrics.mrr_at_k["5"] - fixed.metrics.mrr_at_k["5"], 6),
        },
        "hybrid_vs_dense": {
            "recall_at_5_delta": round(
                hybrid.metrics.recall_at_k["5"] - dense.metrics.recall_at_k["5"], 6
            ),
            "mrr_at_5_delta": round(hybrid.metrics.mrr_at_k["5"] - dense.metrics.mrr_at_k["5"], 6),
        },
        "reranker_vs_hybrid": {
            "recall_at_5_delta": round(
                reranked.metrics.recall_at_k["5"] - hybrid.metrics.recall_at_k["5"], 6
            ),
            "mrr_at_5_delta": round(
                reranked.metrics.mrr_at_k["5"] - hybrid.metrics.mrr_at_k["5"], 6
            ),
            "mean_latency_ms_delta": round(
                reranked.metrics.mean_latency_ms - hybrid.metrics.mean_latency_ms, 6
            ),
        },
        "reranked_failures_at_5": failures,
    }


def _metrics_table(evaluations: dict[str, RetrievalEvaluation]) -> str:
    rows = [
        "| Configuration | Recall@5 | Precision@5 | MRR@5 | NDCG@5 | Mean latency (ms) |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for name, evaluation in evaluations.items():
        metrics = evaluation.metrics
        rows.append(
            f"| {name} | {metrics.recall_at_k['5']:.3f} | "
            f"{metrics.precision_at_k['5']:.3f} | {metrics.mrr_at_k['5']:.3f} | "
            f"{metrics.ndcg_at_k['5']:.3f} | {metrics.mean_latency_ms:.2f} |"
        )
    return "\n".join(rows)


def _write_docs(
    evaluations: dict[str, RetrievalEvaluation],
    comparison: dict[str, object],
    settings: Settings,
) -> None:
    table = _metrics_table(evaluations)
    retrieval_doc = f"""# Retrieval Evaluation

This report is generated by `python -m scripts.evaluate_retrieval` from 30 versioned
queries. Metrics exclude the intentionally unanswerable query from relevance averages.
Latency is local wall-clock time and therefore hardware-dependent.

{table}

## Configuration

- Embeddings: `{settings.embedding_model_name}` at revision `{settings.embedding_model_revision}`
- Vector store: local Qdrant with cosine distance
- Sparse retrieval: Okapi BM25 with lowercase alphanumeric tokenization
- Fusion: Reciprocal Rank Fusion with rank constant 60
- Reranker: `{settings.reranker_model_name}` at revision `{settings.reranker_model_revision}`
- Evaluation depth: top {settings.retrieval_top_k}; candidate depth: {settings.retrieval_candidate_k}

## Interpretation

Dense and BM25 scores are not mixed directly because their scales are unrelated. RRF
combines their ranks. The cross-encoder then reads each query-passage pair and orders the
hybrid candidate set. The full per-query evidence and latency values are stored in
`evaluation/reports/retrieval_v1.json`.

## Diagnostics

```json
{json.dumps(comparison, indent=2, ensure_ascii=False)}
```
"""
    (PROJECT_ROOT / "docs/retrieval-evaluation.md").write_text(
        retrieval_doc,
        encoding="utf-8",
    )

    fixed = evaluations["dense_fixed"].metrics
    recursive = evaluations["dense_recursive"].metrics
    chunking_doc = f"""# Chunking Comparison

Both strategies use {settings.chunk_size_tokens} tokenizer tokens with
{settings.chunk_overlap_tokens} tokens of overlap. Fixed chunking slices token windows;
recursive chunking first preserves Markdown blocks and sentence boundaries, then falls
back to token windows for oversized units.

| Dense configuration | Recall@5 | MRR@5 | Mean latency (ms) |
|---|---:|---:|---:|
| Fixed token | {fixed.recall_at_k["5"]:.3f} | {fixed.mrr_at_k["5"]:.3f} | {fixed.mean_latency_ms:.2f} |
| Recursive | {recursive.recall_at_k["5"]:.3f} | {recursive.mrr_at_k["5"]:.3f} | {recursive.mean_latency_ms:.2f} |

The corpus, chunking code, relevance labels, and reports are committed so this comparison
can be reproduced after any tokenizer or chunk-size change.
"""
    (PROJECT_ROOT / "docs/chunking-comparison.md").write_text(
        chunking_doc,
        encoding="utf-8",
    )


def main() -> None:
    """Build indexes, run all retrieval variants, and persist evidence."""

    settings = Settings()
    fixed_chunks = read_chunks(PROJECT_ROOT / "data/processed/chunks_fixed.jsonl")
    recursive_chunks = read_chunks(PROJECT_ROOT / "data/processed/chunks_recursive.jsonl")
    fixed_queries = _load_labels("fixed")
    recursive_queries = _load_labels("recursive")

    embedder = SentenceTransformerEmbedder(
        settings.embedding_model_name,
        settings.embedding_model_revision,
        settings.retrieval_device,
    )
    qdrant_path = _resolved_path(settings.qdrant_path)
    qdrant_path.parent.mkdir(parents=True, exist_ok=True)
    client = QdrantClient(path=str(qdrant_path))
    try:
        fixed_dense = QdrantDenseRetriever(
            embedder,
            f"{settings.qdrant_collection}_fixed",
            client=client,
        )
        recursive_dense = QdrantDenseRetriever(
            embedder,
            f"{settings.qdrant_collection}_recursive",
            client=client,
        )
        fixed_dense.index(fixed_chunks)
        recursive_dense.index(recursive_chunks)

        bm25 = BM25Retriever(recursive_chunks)
        hybrid = HybridRetriever(
            recursive_dense,
            bm25,
            candidate_k=settings.retrieval_candidate_k,
        )
        scorer = CrossEncoderScorer(
            settings.reranker_model_name,
            settings.reranker_model_revision,
            settings.retrieval_device,
        )
        reranked = RerankedRetriever(
            hybrid,
            scorer,
            candidate_k=settings.retrieval_candidate_k,
        )

        # Exclude one-time model and local-collection startup from steady-state latency.
        fixed_dense.retrieve("latency warmup", top_k=1)
        recursive_dense.retrieve("latency warmup", top_k=1)
        bm25.retrieve("latency warmup", top_k=1)
        hybrid.retrieve("latency warmup", top_k=1)
        scorer.score("latency warmup", [recursive_chunks[0].text])

        evaluations = {
            "dense_fixed": evaluate_retriever(
                fixed_dense,
                fixed_queries,
                max_k=settings.retrieval_top_k,
            ),
            "dense_recursive": evaluate_retriever(
                recursive_dense,
                recursive_queries,
                max_k=settings.retrieval_top_k,
            ),
            "bm25_recursive": evaluate_retriever(
                bm25,
                recursive_queries,
                max_k=settings.retrieval_top_k,
            ),
            "hybrid_recursive": evaluate_retriever(
                hybrid,
                recursive_queries,
                max_k=settings.retrieval_top_k,
            ),
            "reranked_recursive": evaluate_retriever(
                reranked,
                recursive_queries,
                max_k=settings.retrieval_top_k,
            ),
        }
    finally:
        client.close()

    comparison = _comparison(evaluations)
    report = {
        "schema_version": 2,
        "metric_definitions": {
            "recall_at_k": "fraction of labeled relevant chunks retrieved, macro-averaged",
            "hit_rate_at_k": "fraction of answerable queries with at least one relevant hit",
        },
        "corpus": {
            "documents": len({chunk.document_id for chunk in recursive_chunks}),
            "fixed_chunks": len(fixed_chunks),
            "recursive_chunks": len(recursive_chunks),
            "queries": len(recursive_queries),
        },
        "models": {
            "embedding": {
                "name": settings.embedding_model_name,
                "revision": settings.embedding_model_revision,
                "dimension": embedder.dimension,
            },
            "reranker": {
                "name": settings.reranker_model_name,
                "revision": settings.reranker_model_revision,
            },
        },
        "configuration": {
            "top_k": settings.retrieval_top_k,
            "candidate_k": settings.retrieval_candidate_k,
            "qdrant_distance": "cosine",
            "fusion": "reciprocal_rank_fusion",
            "rrf_rank_constant": 60,
        },
        "evaluations": {
            name: evaluation.model_dump(mode="json") for name, evaluation in evaluations.items()
        },
        "comparison": comparison,
    }
    report_path = PROJECT_ROOT / "evaluation/reports/retrieval_v1.json"
    report_path.write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    _write_docs(evaluations, comparison, settings)
    print(_metrics_table(evaluations))
    print(f"\nWrote {report_path}")


if __name__ == "__main__":
    main()
