"""Run the Stage 25 grounded RAG evaluation with a fresh local index."""

import argparse
import hashlib
import json
import platform
import random
from datetime import UTC, datetime
from importlib.metadata import version
from pathlib import Path
from tempfile import TemporaryDirectory
from time import perf_counter
from typing import cast

import numpy as np
import torch
from pydantic import JsonValue

from backend.app.config import Settings
from backend.app.evaluation.rag import evaluate_rag, read_rag_queries, write_rag_evaluation
from backend.app.ingestion.chunkers import HuggingFaceTokenCodec, RecursiveChunker
from backend.app.ingestion.parser import load_documents
from backend.app.ingestion.pipeline import build_chunks, write_chunks
from backend.app.llm.generation import _synchronize
from backend.app.llm.model import resolve_device
from backend.app.rag.factory import build_rag_runtime
from backend.app.rag.generator import LocalGroundedGenerator

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be at least 1")
    return parsed


def _nonnegative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be nonnegative")
    return parsed


def _seed(value: str) -> int:
    parsed = _nonnegative_int(value)
    if parsed > 4_294_967_295:
        raise argparse.ArgumentTypeError("seed must be at most 4294967295")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    """Expose the dataset, output, device, and repeat controls without loading models."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=PROJECT_ROOT / "data/raw")
    parser.add_argument(
        "--queries", type=Path, default=PROJECT_ROOT / "data/evaluation/rag_queries.jsonl"
    )
    parser.add_argument(
        "--output", type=Path, default=PROJECT_ROOT / "evaluation/reports/rag_evaluation_v1.json"
    )
    parser.add_argument("--markdown", type=Path, default=PROJECT_ROOT / "docs/rag-evaluation.md")
    parser.add_argument("--warmup-runs", type=_nonnegative_int, default=1)
    parser.add_argument("--repetitions", type=_positive_int, default=3)
    parser.add_argument("--seed", type=_seed, default=42)
    parser.add_argument("--device", choices=("auto", "cpu", "mps", "cuda"))
    parser.add_argument("--retrieval-device", choices=("auto", "cpu", "mps", "cuda"))
    return parser


def _write_markdown(report_path: Path, evaluation_path: Path) -> None:
    report = json.loads(evaluation_path.read_text(encoding="utf-8"))
    metrics = report["metrics"]
    failures = sorted(
        {
            outcome["query_id"]
            for outcome in report["per_query"]
            if outcome["answerable"] and not outcome["lexical_answer_correct"]
        }
    )
    unsafe = sorted(
        {
            outcome["query_id"]
            for outcome in report["per_query"]
            if not outcome["answerable"] and outcome["status"] == "answered"
        }
    )
    rejected = sorted(
        {outcome["query_id"] for outcome in report["per_query"] if outcome["status"] == "rejected"}
    )
    stage_rows = "\n".join(
        f"| {name} | {value['mean_ms']:.2f} | {value['p50_ms']:.2f} | {value['p95_ms']:.2f} |"
        for name, value in report["latency_by_stage"].items()
    )
    metadata = report["metadata"]
    config = metadata.get("configuration", {})
    markdown = f"""# Stage 25 — RAG Evaluation

Generated by `python -m scripts.evaluate_rag` from {report["dataset_query_count"]} distinct
versioned questions, repeated {report["repetitions"]} time(s). The report contains
{metrics["answerable_query_count"]} answerable and {metrics["unanswerable_query_count"]}
unanswerable measured requests. {report["warmup_runs"]} warmup request(s) are excluded;
{report["warmup_generation_count"]} of those actually generated tokens. Model and index
initialization are excluded from request latency and recorded separately in JSON metadata.

## Answer and evidence results

| Metric | Value |
|---|---:|
| Accepted-answer lexical correctness proxy | {metrics["lexical_answer_correctness"]:.3f} |
| Citation document precision (cited answerable responses) | {metrics["citation_precision"]:.3f} |
| Citation document recall (all answerable requests) | {metrics["citation_recall"]:.3f} |
| Grounding-validator pass and answered rate | {metrics["grounded_answer_rate"]:.3f} |
| Grounded lexical answer rate | {metrics["grounded_lexical_answer_rate"]:.3f} |
| Answerable response rate | {metrics["answerable_response_rate"]:.3f} |
| Answerable abstention rate | {metrics["answerable_abstention_rate"]:.3f} |
| Answerable rejection rate | {metrics["answerable_rejection_rate"]:.3f} |
| Unanswerable abstention accuracy | {metrics["abstention_accuracy"]:.3f} |
| Unanswerable rejection rate | {metrics["unanswerable_rejection_rate"]:.3f} |
| Safe unanswerable rate (abstained or rejected) | {metrics["safe_unanswerable_rate"]:.3f} |
| Unanswerable false-answer rate | {metrics["unanswerable_false_answer_rate"]:.3f} |
| Rejection rate (all requests) | {metrics["rejection_rate"]:.3f} |
| Extractive fallback rate (all requests) | {metrics["extractive_fallback_rate"]:.3f} |

## Latency

| Service phase | Mean ms | p50 ms | p95 ms |
|---|---:|---:|---:|
{stage_rows}

These are service-reported wall-clock phase timings. End-to-end time also includes
orchestration and prompt construction, so phase totals need not equal total latency.
Generation time is the generation adapter's measurement, not HTTP latency. Every measured
request contributes to phase summaries, including zeros for pre-generation abstentions.
Percentiles use NumPy's default linear interpolation; repetitions are repeated measurements
of the same questions, not independent new labels. Hardware, load, and caching affect timings.

## Method and limits

The correctness proxy requires `status == "answered"` and every labeled term as a
case-insensitive substring of the returned answer. `answer_correctness` is retained as a
compatibility alias. `answer_terms_present` is a diagnostic and alone does not imply an
accepted answer. Terms may intentionally be stems such as `revok`; paraphrases can fail,
and contradictory answers containing the terms can pass. This is not semantic correctness,
a human quality review, or an independent faithfulness judge.

Citation precision is a macro average over answerable requests with citations; recall includes
all answerable requests. Citation IDs are deduplicated at document level. Grounding metrics
reuse the production lexical citation validator and therefore measure gate behavior, not
independent factual entailment. Abstentions and rejections are reported separately. Extractive
fallback answers are included in quality metrics and identified per request; the aggregate
measures the entire RAG system, including that fallback, rather than just the language model.

The CLI rechunks the versioned raw corpus and creates a fresh temporary Qdrant index.
Source and chunk SHA-256 fingerprints are recorded. Generation
uses the production greedy settings. Dataset and corpus hashes, model revisions, resolved
language-model runtime, package versions, seed, requested devices, settings, and load time
are included in the JSON report. The evaluation uses the production recursive pipeline;
chunk-size comparisons belong to Stage 24. No thresholds are tuned against these labels.
The small curated dataset does not establish performance on a broader query distribution.

## Reproduce

```bash
python -m scripts.evaluate_rag --warmup-runs 1 --repetitions 3 --seed 42
# Optional device and repeated-latency measurement:
python -m scripts.evaluate_rag --device cpu --retrieval-device cpu --repetitions 3 \\
  --output evaluation/reports/rag_evaluation_cpu.json --markdown docs/rag-evaluation-cpu.md
```

Current run configuration:

```json
{json.dumps(config, indent=2, ensure_ascii=False)}
```

## Diagnostics

- Answerable queries with at least one failed lexical answer: `{failures}`
- Unanswerable queries with at least one returned answer: `{unsafe}`
- Queries with at least one grounding rejection: `{rejected}`

Complete per-request labels, missing terms, raw and returned answers, citation snippets and
chunk/document IDs, token counts, phase timings, and validator issues: `{evaluation_path}`.
"""
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(markdown, encoding="utf-8")


def main(argv: list[str] | None = None) -> None:
    """Run real local inference and save the report after closing runtime resources."""

    parser = build_parser()
    args = parser.parse_args(argv)
    if args.output.resolve() == args.markdown.resolve():
        parser.error("JSON and Markdown output paths must differ")
    if not args.corpus.is_dir():
        parser.error(f"Corpus directory does not exist: {args.corpus}")
    queries = read_rag_queries(args.queries)
    documents = load_documents(args.corpus)
    if not documents:
        parser.error("Corpus must contain supported, nonempty documents")
    known_documents = {document.document_id for document in documents}
    if any(set(query.relevant_document_ids) - known_documents for query in queries):
        parser.error("All RAG source labels must refer to documents in the corpus")
    settings_data = Settings().model_dump()
    if args.device is not None:
        settings_data["device"] = args.device
    if args.retrieval_device is not None:
        settings_data["retrieval_device"] = args.retrieval_device
    settings = Settings.model_validate(settings_data)
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    configuration = {
        key: value
        for key, value in settings.model_dump(mode="json").items()
        if key.startswith(("rag_", "retrieval_", "embedding_", "reranker_", "model_"))
        or key == "device"
    }
    metadata: dict[str, JsonValue] = {
        "created_at_utc": datetime.now(UTC).isoformat(),
        "dataset_path": str(args.queries.resolve()),
        "dataset_sha256": hashlib.sha256(args.queries.read_bytes()).hexdigest(),
        "corpus_path": str(args.corpus.resolve()),
        "corpus_sha256": hashlib.sha256(
            "\n".join(document.model_dump_json() for document in documents).encode("utf-8")
        ).hexdigest(),
        "configuration": cast(JsonValue, configuration),
        "seed": args.seed,
        "index_policy": "fresh_temporary_recursive_cosine_index",
        "decoding": {"do_sample": False, "repetition_penalty": 1.05},
        "python": platform.python_version(),
        "platform": platform.platform(),
        "machine": platform.machine(),
        "torch_num_threads": torch.get_num_threads(),
        "packages": {
            package: version(package)
            for package in (
                "torch",
                "transformers",
                "sentence-transformers",
                "qdrant-client",
                "numpy",
            )
        },
    }
    with TemporaryDirectory(prefix="rag-evaluation-") as evaluation_directory:
        evaluation_root = Path(evaluation_directory)
        started = perf_counter()
        codec = HuggingFaceTokenCodec.from_pretrained(settings.model_name, settings.model_revision)
        chunker = RecursiveChunker(codec, settings.chunk_size_tokens, settings.chunk_overlap_tokens)
        chunks = build_chunks(documents, chunker)
        chunks_path = evaluation_root / "data/processed/chunks_recursive.jsonl"
        write_chunks(chunks_path, chunks)
        metadata["corpus_preparation_ms"] = round((perf_counter() - started) * 1_000, 6)
        metadata["chunks_sha256"] = hashlib.sha256(chunks_path.read_bytes()).hexdigest()
        metadata["chunking"] = {
            "strategy": "recursive",
            "size_tokens": chunker.chunk_size,
            "overlap_tokens": chunker.overlap,
            "chunk_count": len(chunks),
            "tokenizer": settings.model_name,
            "tokenizer_revision": settings.model_revision,
        }
        settings = settings.model_copy(update={"qdrant_path": evaluation_root / "qdrant"})
        started = perf_counter()
        runtime = build_rag_runtime(settings, project_root=evaluation_root)
        try:
            _synchronize(resolve_device(settings.device))
            _synchronize(resolve_device(settings.retrieval_device))
            metadata["runtime_initialization_ms"] = round((perf_counter() - started) * 1_000, 6)
            generator = runtime.service.generator
            if isinstance(generator, LocalGroundedGenerator):
                generator.options = generator.options.model_copy(update={"seed": args.seed})
                metadata["generation_runtime"] = cast(JsonValue, generator.runtime.metadata())
                metadata["decoding"] = cast(JsonValue, generator.options.model_dump(mode="json"))
            evaluation = evaluate_rag(
                runtime.service,
                queries,
                warmup_runs=args.warmup_runs,
                repetitions=args.repetitions,
                metadata=metadata,
            )
        finally:
            runtime.close()

    write_rag_evaluation(args.output, evaluation)
    _write_markdown(args.markdown, args.output)
    print(json.dumps(evaluation.metrics.model_dump(mode="json"), indent=2))
    print(f"Wrote {args.output}")
    print(f"Wrote {args.markdown}")


if __name__ == "__main__":
    main()
